construction_obj/urls.py
from django.urls import path

from construction_obj.views import (
    ListBuildingView,
    DetailBuildingView,
    UpdateSectionView,
)

app_name = "construction_obj"

urlpatterns = [
    path("", ListBuildingView.as_view(), name="list_buildings"),
    path("building/<int:pk>/", DetailBuildingView.as_view(), name="detail_building"),
    path("update_section/<int:pk>/", UpdateSectionView.as_view(), name="update_section"),
]

edtech/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include("construction_obj.urls")),
    path("__debug__/", include(debug_toolbar.urls)),

]

construction_obj/models.py
from django.db import models
from django.core.exceptions import ValidationError


class Building(models.Model):
    """
    Модель объекта строительства.
    """

    name = models.CharField(max_length=50, verbose_name="наименование объекта")

    class Meta:
        verbose_name = "объект строительства"
        verbose_name_plural = "объекты строительства"

    def __str__(self):
        return self.name


class Section(models.Model):
    """
    Модель секций сметы.
    """

    name = models.CharField(max_length=50, verbose_name="название сметы")
    building = models.ForeignKey(
        Building, on_delete=models.PROTECT, verbose_name="объект строительства"
    )
    parent = models.ForeignKey(
        "self",
        on_delete=models.PROTECT,
        verbose_name="родительская секция",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "секция сметы"
        verbose_name_plural = "секции смет"

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        """Перед сохранением проверяем на уровень вложенности."""
        if not self.id and self.parent and getattr(self.parent, "parent", None):
            raise ValidationError("Максимальный уровень вложенности 2")
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        if self.parent:
            return "{parent} - {name}".format(
                parent=self.parent,
                name=self.name
            )
        return "{name}: {object_name}".format(
            name=self.name,
            object_name=self.building.name
        )


class Expenditure(models.Model):
    """
    Модель стоимости сметы.
    """

    class Types:
        WORK = "work"
        MATERIAL = "material"
        choices = (
            (WORK, "Работа"),
            (MATERIAL, "Материал"),
        )

    section = models.ForeignKey(
        Section,
        on_delete=models.PROTECT,
        help_text="Расценка может принадлежать "
        "только той секции, у которой указан parent",
    )
    name = models.CharField(max_length=50, verbose_name="название расценки")
    type = models.CharField(
        verbose_name="тип расценки", choices=Types.choices, max_length=8
    )
    count = models.DecimalField(
        verbose_name="кол-во", max_digits=20, decimal_places=8
    )
    price = models.DecimalField(
        verbose_name="цена за единицу", max_digits=20, decimal_places=2
    )

    class Meta:
        verbose_name = "расценка сметы"
        verbose_name_plural = "расценки смет"

construction_obj/forms.py
from django.contrib.auth.forms import forms


class DiscountForms(forms.Form):
    """Форма для ввода скидки."""

    discount = forms.DecimalField(
        label="Скидка",
        min_value=0,
        max_value=100,
        decimal_places=2,
        help_text="Введите размер скидки, % (от 0 до 100):",
    )

construction_obj/views.py
from decimal import Decimal

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView

from construction_obj.forms import DiscountForms
from construction_obj.services import (
    get_parent_sections,
    get_buildings,
    update_with_discount,
)


class ListBuildingView(ListView):
    """
    Список всех объектов с подсчитанными
    затратами на строительство.
    """

    template_name = "construction_obj/list_building.html"
    context_object_name = "buildings"

    def get_queryset(self):
        query = get_buildings()
        return query


class DetailBuildingView(ListView):
    """
    Детальная информация об объекте с секциями и общей стоимостью затрат.
    """

    template_name = "construction_obj/detail_building.html"
    context_object_name = "sections"

    def get_queryset(self):
        obj_id = self.kwargs["pk"]
        query = get_parent_sections(building_id=obj_id)
        return query


class UpdateSectionView(FormView):
    """
    Применение скидки к стоимости секции.
    """

    template_name = "construction_obj/update_section.html"
    success_url = reverse_lazy("construction_obj:list_buildings")
    form_class = DiscountForms

    def form_valid(self, form):
        section_id = self.kwargs["pk"]
        discount = Decimal(self.request.POST.get("discount"))
        update_with_discount(
            section_id=section_id,
            discount=discount
        )
        return HttpResponseRedirect(self.success_url)

templates/construction_obj/detail_building.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Задача 1 - Информация о главных секциях сметы</title>
</head>
<body>
{% if sections|length > 0 %}
    {% for section in sections %}
        <p>ID - {{ section.parent_id }}</p>
        <p>Название - {{ section.parent__name }}</p>
        <p>Стоимость - {{ section.total_price }}</p>
        {% if section.total_price > 0 %}
            <button type="submit">
                <a href="{% url 'construction_obj:update_section' pk=section.parent_id %}">Добавить скидку</a>
            </button>
        {% endif %}
        <hr>
    {% endfor %}
{% else %}
    <h3>Данные о смете не добавлены.</h3>
{% endif %}
</body>
</html>

templates/construction_obj/list_building.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Задача 2 - Получение всех объектов с расчетом стоимости работ и материалов</title>
</head>
<body>
{% for obj in buildings %}
    <ul>
        <li><a href="{% url "construction_obj:detail_building" pk=obj.pk %}">ID{{ obj.pk }} - {{ obj.name }}</a></li>
            <p>Стоимость работ - {% if obj.works_amount %}{{ obj.works_amount }}{% else %}...{% endif %}</p>
            <p>Стоимость материалов - {% if obj.materials_amount %}{{ obj.materials_amount }}{% else %}...{% endif %}</p>
    </ul>
    <hr>
{% endfor %}
</body>
</html>

templates/construction_obj/update_section.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Задача 3 - Применения скидки к секции.</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Применить</button>
</form>

</body>
</html>